import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import posts from '../../public/posts.json'
import { useRouter } from 'next/router'

export default function Blog() {
    const router = useRouter()

    const post = posts[router.query.id]

    if(!post) return <p></p>

    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
                Single Post Page
            </h1>
            <p><b>Title:</b> {post.title}</p>
            <p><b>Content:</b> {post.content}</p>
        </main>      
        </div>
    )
}
